import = ["~/.config/alacritty/themes/themes/challenger_deep.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new -s main"]

[font]
size = 16.5

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
padding = { x = 5, y = 0 }
opacity = 0.96
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"
